version: '3'

services:
  face_recognition:
    image: face_recognition_on_rasp
    container_name: face_recognition

    build:
      context: .
      dockerfile: Dockerfile.rasp



    volumes:
      - ./root/face_recognition/mm_application:/face_recognition/mm_application_volume

    working_dir: /face_recognition/mm_application_volume
    command: python3 facerec_on_rasp_usb_camera.py

    devices:
      - dev/video0:dev/video0

    privileged: true
    # direct logging to terminal, no buffering for logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/face_recognition/mm_application

networks:
  mqtt_network:
    external: true