version: '3'

services:
  face_recognition:
    image: face_recognition_on_rasp
    container_name: face_recognition

    build:
      context: .
      dockerfile: Dockerfile.rasp

    volumes:
      - ./mm_application:/root/face_recognition/mm_application_volume
    network_mode: host

    working_dir: /face_recognition/mm_application_volume
    command: python3 facerec_on_rasp_usb_camera.py

    devices:
      - dev/video0:dev/video0

    privileged: true
    # direct logging to terminal, no buffering for logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/root/face_recognition/mm_application
