version: '3'

services:
  face_recognition:
    image: face_recognition_on_rasp
    container_name: face_recognition

    build:
      context: .
      dockerfile: Dockerfile.rasp

    working_dir: /face_recognition/mm_application
    command: python3 facerec_on_rasp_usb_camera.py

    volumes:
      - ./:/face_recognition

    devices:
      - dev/video0:dev/video0
    # direct logging to terminal, no buffering for logs
    environment:
      - PYTHONUNBUFFERED=1