version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/examples
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=1
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu 
    command: python3 recognize_faces_in_pictures.py
    volumes:
      - ./:/face_recognition
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    # runtime: nvidia